DROP TABLE `aiChatConversations`;--> statement-breakpoint
DROP TABLE `aiChatMessages`;--> statement-breakpoint
DROP TABLE `aiInsights`;--> statement-breakpoint
DROP TABLE `availabilityExceptions`;--> statement-breakpoint
DROP TABLE `clients`;--> statement-breakpoint
DROP TABLE `coachAvailability`;--> statement-breakpoint
DROP TABLE `coachGuidance`;--> statement-breakpoint
DROP TABLE `coachNotifications`;--> statement-breakpoint
DROP TABLE `coaches`;--> statement-breakpoint
DROP TABLE `complianceFlags`;--> statement-breakpoint
DROP TABLE `copingStrategies`;--> statement-breakpoint
DROP TABLE `discountCodeUsage`;--> statement-breakpoint
DROP TABLE `discountCodes`;--> statement-breakpoint
DROP TABLE `emotionLogs`;--> statement-breakpoint
DROP TABLE `escalationQueue`;--> statement-breakpoint
DROP TABLE `journalEntries`;--> statement-breakpoint
DROP TABLE `liveSessionTranscripts`;--> statement-breakpoint
DROP TABLE `platformSettings`;--> statement-breakpoint
DROP TABLE `sessionReminders`;--> statement-breakpoint
DROP TABLE `sessionTypes`;--> statement-breakpoint
DROP TABLE `sessions`;--> statement-breakpoint
DROP TABLE `similarCases`;--> statement-breakpoint
DROP TABLE `subscriptions`;--> statement-breakpoint
DROP TABLE `videoTestimonials`;--> statement-breakpoint
DROP TABLE `dailyCheckins`;--> statement-breakpoint
DROP TABLE `disciplineEvents`;--> statement-breakpoint
DROP TABLE `habitCompletions`;--> statement-breakpoint
DROP TABLE `habits`;--> statement-breakpoint
DROP TABLE `identityProfiles`;--> statement-breakpoint
DROP TABLE `microHabits`;--> statement-breakpoint
DROP TABLE `clientPatterns`;--> statement-breakpoint
DROP TABLE `outcomeTracking`;--> statement-breakpoint
DROP TABLE `recommendationFeedback`;--> statement-breakpoint
DROP TABLE `strategyAdjustments`;--> statement-breakpoint
DROP TABLE `techniqueEffectiveness`;--> statement-breakpoint
DROP TABLE `trendDetection`;--> statement-breakpoint
DROP TABLE `autismOutcomeTracking`;--> statement-breakpoint
DROP TABLE `autismPatternDetection`;--> statement-breakpoint
DROP TABLE `autismProfiles`;--> statement-breakpoint
DROP TABLE `autismProviders`;--> statement-breakpoint
DROP TABLE `dietaryInterventions`;--> statement-breakpoint
DROP TABLE `interventionPlans`;--> statement-breakpoint
DROP TABLE `supplementTracking`;--> statement-breakpoint
DROP TABLE `therapySessions`;